Add support for uncompressed bit along with tests
composewell/streamly-lz4 pull request #26
Opened 2021-01-12 19:05 UTC by adithyaov

2021-01-12 19:54 UTC, harendra-kumar requested changes

2021-01-12 19:54 UTC, harendra-kumar commented on src/Streamly/Internal/LZ4.hs
> +              else do
I think we should do this inside `decompressChunk` itself instead of doing it outside.

2021-01-12 19:54 UTC, harendra-kumar commented on test/Main.hs
> +        hdr = Array.fromList [negLen, negLen]
Uncompressed length should be positive. How is this working? It seems we are not doing any checks on that anywhere, in this code path? We should catch this somewhere.

2021-01-23 01:51 UTC, adithyaov commented
Am closing this as it is not required as of now.

2021-01-23 01:51 UTC, closed without merging